apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
  namespace: myapp
  labels:
    app: springboot
spec:
  containers:
  - name: springboot
    image: silversabon/marwasabon_java_apps:latest
    ports:
    - containerPort: 8030
    env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://mysql-service:3306/shortcode
    - name: SPRING_DATASOURCE_USERNAME
      value: root
    - name: SPRING_DATASOURCE_PASSWORD
      value: password
